server:
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_general_ci

  jpa:
    database: mysql
    open-in-view: true
    properties:
      hibernate:
        use-new-id-generator-mappings: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        search:
          lucene_version: LATEST
    hibernate:
      ddl-auto: update
    show-sql: false

  cache:
    jcache:
      config: classpath:ehcache.xml

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: Светловка
    - url: https://dimonvideo.ru/
      name: ДимонВидео
    - url: https://playback.ru/
      name: ПлейБек
